name: Validate meetup info
description: Validate date information inside frontmatter

inputs:
  paths:
    required: true

runs:
  using: composite
  steps:
    - name: Restore binary
      id: restore-cache
      uses: actions/cache/restore@v4
      with:
        path: .bin/validate-meetup-info
        key: validate-meetup-info-bin-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('.github/actions/validate-meetup-info/**/*') }}

    - name: Setup go
      uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
      if: steps.restore-cache.outputs.cache-hit != 'true'
      with:
        check-latest: true
        cache-dependency-path: |
          .github/actions/validate-meetup-info/go.sum
        go-version-file: ".github/actions/validate-meetup-info/go.mod"

    - name: Build binary
      if: steps.restore-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        set -e
        mkdir .bin
        cd ${{ github.action_path }}
        go build -o ../../../.bin/validate-meetup-info

    - name: Cache binary
      if: steps.restore-cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: .bin/validate-meetup-info
        key: validate-meetup-info-bin-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('.github/actions/validate-meetup-info/**/*') }}

    - name: Run validation
      shell: bash
      run: |
        ./.bin/validate-meetup-info ${{ inputs.paths }}

