name: Validate meetup info

on:
  pull_request:
    paths:
      - "content/meetup/*.md"
      - ".github/workflows/validate-meetup-info.yaml"
      - ".github/actions/validate-meetup-info/**/*"

jobs:
  validate-meetup-info:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493 # v4.2.2
      - uses: ./.github/actions/validate-meetup-info
        with:
          paths: |
            content/meetup/*.md
